brewery:
  name: Hutsnz Brewery

fermenters:
  - id: 1
    name: Fridge
    sensorId: 28-041752558aff
    targetTemp: 21
    gpioHeat: 1
    gpioCool: 2
  - id: 2
    name: Test
    sensorId: "28-041752558aff"
    targetTemp: 18
    gpioHeat: 3
    gpioCool: 4
kettles:
  - id: 3
    name: Kettle1
mashtuns:
  - id: 4
    name: Mash Tun 1
    