brewery:
  name: Raspbeery Pi

device:
  - id: 0
    name: Kettle
    active: True
    sensor_id: 28-041752558aff
    target_temperature: 21
    gpio_heat: 1
    id: 1
    name: Fridge
    active: True
    sensor_id: 28-041752558aff
    target_temperature: 21
    gpio_heat: 2
    gpio_cool: 3
    